# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cad30e4443c753aa291a18823328aebab15d7b23653b5053b9c39fb5830c177d653e21a61203cf059dca56bc0ac2aff45c36ddfce732f574a3fa8bb41b4b91c

test:
  secret_key_base: c152466716373526ad99755fb8a2d36db139001de218fc4db97a4209e8193ba2951851642f1291335ac36964733563dc83a25e764c0e6ea94791b5f7e15787a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
